#!/bin/bash

# OpenTelemetry AKS Demo - Setup Script
# This script creates all Azure resources needed for the demo

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored output
print_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

# Check if config.env exists
if [ ! -f "config.env" ]; then
    print_error "config.env file not found!"
    print_info "Please create config.env with your Azure configuration."
    print_info "See config.env.example for template."
    exit 1
fi

# Load configuration
source config.env

# Validate required variables
REQUIRED_VARS=("SUBSCRIPTION_ID" "RESOURCE_GROUP" "LOCATION" "AKS_CLUSTER_NAME" "ACR_NAME" "APP_INSIGHTS_NAME" "NAMESPACE")
for var in "${REQUIRED_VARS[@]}"; do
    if [ -z "${!var}" ]; then
        print_error "Required variable $var is not set in config.env"
        exit 1
    fi
done

print_info "Starting Azure resources setup..."
print_info "Configuration:"
echo "  Subscription: $SUBSCRIPTION_ID"
echo "  Resource Group: $RESOURCE_GROUP"
echo "  Location: $LOCATION"
echo "  AKS Cluster: $AKS_CLUSTER_NAME"
echo "  ACR: $ACR_NAME"
echo "  App Insights: $APP_INSIGHTS_NAME"
echo "  Namespace: $NAMESPACE"
echo ""

read -p "Continue with this configuration? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    print_info "Setup cancelled."
    exit 0
fi

# Set active subscription
print_info "Setting active subscription..."
az account set --subscription $SUBSCRIPTION_ID

# Create resource group
print_info "Creating resource group '$RESOURCE_GROUP'..."
az group create \
  --name $RESOURCE_GROUP \
  --location $LOCATION \
  --output none

# Create ACR
print_info "Creating Azure Container Registry '$ACR_NAME'..."
az acr create \
  --resource-group $RESOURCE_GROUP \
  --name $ACR_NAME \
  --sku ${ACR_SKU:-Basic} \
  --output none

print_info "Logging in to ACR..."
az acr login --name $ACR_NAME

# Get ACR login server
export ACR_LOGIN_SERVER=$(az acr show --name $ACR_NAME --query loginServer -o tsv)
print_info "ACR Login Server: $ACR_LOGIN_SERVER"

# Create AKS cluster
print_info "Creating AKS cluster '$AKS_CLUSTER_NAME'..."
print_warning "This may take 5-10 minutes..."

az aks create \
  --resource-group $RESOURCE_GROUP \
  --name $AKS_CLUSTER_NAME \
  --node-count ${AKS_NODE_COUNT:-2} \
  --node-vm-size ${AKS_NODE_SIZE:-Standard_DS2_v2} \
  --enable-managed-identity \
  --attach-acr $ACR_NAME \
  --enable-azure-monitor-metrics \
  --enable-azure-monitor-app-monitoring \
  --generate-ssh-keys \
  --output none

print_info "Getting AKS credentials..."
az aks get-credentials \
  --resource-group $RESOURCE_GROUP \
  --name $AKS_CLUSTER_NAME \
  --overwrite-existing

print_info "Verifying AKS connection..."
kubectl get nodes

# Create Application Insights
print_info "Creating Application Insights '$APP_INSIGHTS_NAME'..."
print_info "Note: Application Insights created via CLI has OTLP ingestion enabled by default"
az monitor app-insights component create \
  --app $APP_INSIGHTS_NAME \
  --location $LOCATION \
  --resource-group $RESOURCE_GROUP \
  --application-type web \
  --output none

print_info "Verifying Application Insights was created with OTLP support..."

# Get Application Insights details
export APP_INSIGHTS_CONNECTION_STRING=$(az monitor app-insights component show \
  --app $APP_INSIGHTS_NAME \
  --resource-group $RESOURCE_GROUP \
  --query connectionString -o tsv)

export APP_INSIGHTS_APP_ID=$(az monitor app-insights component show \
  --app $APP_INSIGHTS_NAME \
  --resource-group $RESOURCE_GROUP \
  --query appId -o tsv)

print_info "Application Insights created successfully!"
echo "  Connection String: $APP_INSIGHTS_CONNECTION_STRING"
echo "  App ID: $APP_INSIGHTS_APP_ID"

# Save outputs to file
cat > setup-outputs.env <<EOF
# Generated by setup.sh on $(date)
export ACR_LOGIN_SERVER="$ACR_LOGIN_SERVER"
export APP_INSIGHTS_CONNECTION_STRING="$APP_INSIGHTS_CONNECTION_STRING"
export APP_INSIGHTS_APP_ID="$APP_INSIGHTS_APP_ID"
EOF

print_info "Setup outputs saved to setup-outputs.env"

# Configure namespace
print_info "Creating namespace '$NAMESPACE' with auto-configuration..."
kubectl create namespace $NAMESPACE || print_warning "Namespace already exists"

kubectl annotate namespace $NAMESPACE \
  instrumentation.opentelemetry.io/inject-configuration="true" \
  --overwrite

# Create Instrumentation CR
print_info "Creating Instrumentation custom resource..."
cat <<EOF | kubectl apply -f -
apiVersion: monitor.azure.com/v1
kind: Instrumentation
metadata:
  name: default
  namespace: $NAMESPACE
spec:
  destination:
    applicationInsightsConnectionString: "$APP_INSIGHTS_CONNECTION_STRING"
  settings:
    autoInstrumentationPlatforms: []
EOF

# Verify Instrumentation CR
print_info "Verifying Instrumentation CR..."
kubectl get instrumentation -n $NAMESPACE

# Restart AMA pods to pick up the new Instrumentation CR
print_info "Restarting Azure Monitor Agent pods to pick up configuration..."
kubectl delete pods -n kube-system -l rsName=ama-logs
print_info "Waiting for AMA pods to restart..."
sleep 10
kubectl wait --for=condition=ready pod -l rsName=ama-logs -n kube-system --timeout=120s || print_warning "Some AMA pods may still be starting"

print_info ""
print_info "=========================================="
print_info "Azure resources setup completed!"
print_info "=========================================="
print_info ""
print_info "Next steps:"
print_info "  1. Build and push Docker images: ./scripts/build-and-push.sh"
print_info "  2. Deploy applications: ./scripts/deploy.sh"
print_info "  3. Access the application and generate traffic"
print_info "  4. View telemetry in Application Insights (wait 3-5 minutes)"
print_info ""
print_info "To view Application Insights in the portal:"
APP_INSIGHTS_ID=$(az monitor app-insights component show \
  --app $APP_INSIGHTS_NAME \
  --resource-group $RESOURCE_GROUP \
  --query id -o tsv)
print_info "  https://portal.azure.com/#@/resource$APP_INSIGHTS_ID/overview"
print_info ""
